version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: "com.amazonaws:aws-java-sdk-s3"
        update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]