version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:30"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "16:30"
    ignore:
      - dependency-name: "com.amazonaws:aws-java-sdk-s3"
        update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
