version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - update-types: [ "version-update:semver-patch", "version-update:semver-minor" ]
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly