version: '3'
services:
  fs-test-minio:
    image: minio/minio
    ports:
      - "11000:9000"
    environment:
      MINIO_ACCESS_KEY: minio_key
      MINIO_SECRET_KEY: minio_secret
    command: server /sandbox