name: Release
on:
  release:
    types: [ published ]

jobs:
  release1:
    name: Release
    uses: qcastel/github-actions-maven-release@v1.12.41
    with:
      ssh-private-key: ${{ secrets.ACTION_MAVEN_KEY }}
      gpg-enabled: true
      gpg-key-id: ${{ secrets.ACTIONS_RELEASE_GPG_ID }}
      gpg-key: ${{ secrets.ACTIONS_RELEASE_GPG_KEY }}
      gpg-passphrase: ${{ ACTIONS_RELEASE_GPG_PASSPHRASE }}
      git-release-bot-name: "GitHub Actions"
      git-release-bot-email: "actions@github.com"