name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Prepare next release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTION_PAT }}
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven
      - name: Release package
        run: |
          mvn -B clean install -DskipTests
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mvn -B release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}