name: Release
on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test run 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven
      - name: Maven verify
        run: mvn -B verify

  release:
    name: Release and deploy 📦
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: maven
      - name: Release package
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mvn -B release:prepare
          mvn -B release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}