name: Release
on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test run 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven
      - name: Maven verify
        run: mvn -B verify

  release:
    name: Release and deploy 📦
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven
      - name: Publish package
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}