name: Release
on:
  release:
    types: [ published ]

jobs:
  test:
    name: Test run 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven
      - name: Maven verify
        run: mvn -B verify

  release:
    name: Release and deploy 📦
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      repository-projects: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
          cache: maven
      - name: Release package
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "GitHub Actions"
          git-release-bot-email: "actions@github.com"
          ssh-private-key: ${{ secrets.ACTIONS_MAVEN_KEY }}
          maven-args: "-DskipTests"