name: Publish package to GitHub Packages
on: [ pull_request ]

jobs:
  test:
    name: Test run 🧪
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Maven verify
        run: mvn -B verify